# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14neiTGxalbucK5QN9aLZ6SIGJrcni57I
"""

import streamlit as st
import pickle
import numpy as np

# Load the model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

# Sidebar navigation
st.sidebar.title("🌼 Navigation")
page = st.sidebar.radio("Go to", ["Home", "Predict", "About"])

# --- HOME PAGE ---
if page == "Home":
    st.title("🌸 Iris Species Prediction App")
    st.write("""
    Welcome to the **Iris Flower Classifier** built with Streamlit!

    This app uses a trained machine learning model to predict the species of an Iris flower based on its features.

    **Pages available:**
    - 🏠 Home
    - 🔍 Predict
    - 📘 About
    """)

# --- PREDICT PAGE ---
elif page == "Predict":
    st.title("🔍 Predict Iris Species")

    # Input sliders
    sepal_length = st.slider('Sepal length (cm)', 4.0, 8.0, 5.1)
    sepal_width = st.slider('Sepal width (cm)', 2.0, 4.5, 3.5)
    petal_length = st.slider('Petal length (cm)', 1.0, 7.0, 1.4)
    petal_width = st.slider('Petal width (cm)', 0.1, 2.5, 0.2)

    if st.button("Predict"):
        input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        st.success(f"🌼 The predicted species is: **{prediction}**")

# --- ABOUT PAGE ---
elif page == "About":
    st.title("📘 About This App")

    st.write("""
    This Streamlit app was created to demonstrate a simple machine learning deployment.

    - **Model:** Random Forest Classifier
    - **Dataset:** Iris (includes 3 species: Setosa, Versicolor, Virginica)
    - **Model Format:** `.pkl` (Pickle)

    Developed for demo and learning purposes.
    """)